version: '3.3'
services:
    node-js-backend-app:
        depends_on:
            - mongodb
        ports:
            - ${NODE_DOCKER_PORT}:3030
        env_file: ../.env
        volumes:
            - ${APPLICATION_VOLUME}:/home/node/app
        image: kapilpundit/node-js-backend-app:0.0.1
        environment:
            - DB_HOST=${MONGODB_DB_HOST}
            - DB_USER=${MONGODB_USER}
            - DB_PASSWORD=${MONGODB_PASSWORD}
            - DB_NAME=${MONGODB_DATABASE}
            - DB_PORT=${MONGODB_DOCKER_PORT}

    mongodb:
        image: mongo:5.0.2
        restart: unless-stopped
        env_file: ../.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        ports:
            - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
        volumes:
            - db:/data/db

volumes:
  db:
